apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc-tech
  labels:
    app: abc-tech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abc-tech
  template:
    metadata:
      labels:
        app: abc-tech
    spec:
      containers:
        - name: abc-tech
          image: "${IMAGE_NAME}:${IMAGE_TAG}"   # important: quoted
          ports:
            - containerPort: 8080
